models/ContactForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

/**
 * ContactForm is the model behind the contact form.
 */
class ContactForm extends Model
{
    public $name;
    public $email;
    public $subject;
    public $body;
    public $verifyCode;


    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            // name, email, subject and body are required
            [['name', 'email', 'subject', 'body'], 'required'],
            // email has to be a valid email address
            ['email', 'email'],
            // verifyCode needs to be entered correctly
            ['verifyCode', 'captcha'],
        ];
    }

    /**
     * @return array customized attribute labels
     */
    public function attributeLabels()
    {
        return [
            'verifyCode' => 'Verification Code',
        ];
    }

    /**
     * Sends an email to the specified email address using the information collected by this model.
     * @param string $email the target email address
     * @return bool whether the model passes validation
     */
    public function contact($email)
    {
        if ($this->validate()) {
            Yii::$app->mailer->compose()
                ->setTo($email)
                ->setFrom([$this->email => $this->name])
                ->setSubject($this->subject)
                ->setTextBody($this->body)
                ->send();

            return true;
        }
        return false;
    }
}

models/LoginForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

/**
 * LoginForm is the model behind the login form.
 *
 * @property User|null $user This property is read-only.
 *
 */
class LoginForm extends Model
{
    public $username;
    public $password;
    public $curlname;
    public $rememberMe = true;
    private $_user = false;

    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            // username and password are both required
            [['username', 'password','curlname'], 'required'],
            // rememberMe must be a valid email
            ['username', 'email'],
            // rememberMe must be a boolean value
            ['rememberMe', 'boolean'],
        ];
    }

    /**
     * Logs in a user using the provided username and password.
     * @return bool whether the user is logged in successfully
     */
    public function login()
    {
        if ($this->validate()) {
            return Yii::$app->user->login($this->getUser(), $this->rememberMe ? 3600*24*30 : 0);
        }
        return false;
    }

}

models/ShamanLoginForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;
use app\models\ShamanUser;
/**
 * ShamanLoginForm is the model behind the login form.
 *
 * @property User|null $user This property is read-only.
 *
 */
class ShamanLoginForm extends Model
{
    public $email;
    public $password;
    public $curlname;
    public $rememberMe = true;
    
    private $_user= false;

    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            [['email', 'password','curlname'], 'required'],
            ['email', 'email'],
        ];
    }

    /**
     * Logs in a user using the provided username and password.
     * @return bool whether the user is logged in successfully
     */
    public function login()
    {
        if ($this->validate()) {
            return Yii::$app->user->login($this->getUser(), $this->rememberMe ? 3600*24*30 : 0);
        }
        return false;
    }
    
    /**
     * Finds user by [[username]]
     *
     * @return User|null
     */
    private function getUser()
    {
        if ($this->_user === false) {
            $this->_user = ShamanUser::findByEmail($this->email);
                        
        }
        return $this->_user;
    }
}

models/ShamanUser.php
<?php

namespace app\models;

class ShamanUser extends \yii\base\Object implements \yii\web\IdentityInterface
{
    public $id;
    public $email;
    public $password;
    public $curlname;
    public $authKey;
    public $accessToken;

    private static $users = [
        '100' =>[
                'id' => '1',
                'email' => 'test@user.demo',
                'password' => '1234567A',
                'curlname' => 'web-2015',
                'authKey'  => 'test100key',
                'accessToken' => '100-token',
            ]
        ];
    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        foreach (self::$users as $user)
        {
            if($user['id'] == $id)
                return new static($user);
            return null;
        }
    }
    
    public static function findByEmail($email)
    {
        foreach (self::$users as $user)
        {
            if($user['email'] == $email)
                return new static($user);
            return null;
        }
    }
    
}

controllers/ShamanController.php
<?php
namespace app\controllers;

use yii\filters\AccessControl;
use yii\web\Controller;
use app\models\ShamanLoginForm;

class ShamanController extends Controller
{
    public function actionIndex()
    {
        $model = new ShamanLoginForm();
        return $this->render('login',['model' => $model]);
    }
    public function actionLogin()
    {
        $request = \Yii::$app->request;
        if ($request->isPost)
        {
            $rsp = \app\services\ShamanService::getToken($request->post());
            return $rsp;
        }
    }

    public function actionUser()
    {
        $request = \Yii::$app->request;
        if ($request->isPost)
        {
            $rsp = \app\services\ShamanService::getUserByToken($request->post('token'));
            return $rsp;
        }
    }

    public function actionInfoSecretKey()
    {
        $request = \Yii::$app->request;
        if ($request->isPost)
        {
            $rsp = \app\services\ShamanService::getInfoSecretKey($request->post('secretKey'));
            return $rsp;
        }
    }
    
    
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\ShamanLoginForm;
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'My Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/shaman']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->email . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/shaman/info.php
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<?php


$secretKey = 'Q29uZ3JhdHMsIHlvdSd2ZSBkb25lIGl0';





exit;








use yii\helpers\Html;
use yii\widgets\ActiveForm;

$form = ActiveForm::begin([
    'id' => 'shaman-login',
    'options' => ['class' => ''],
    'action' =>'https://api.shamandev.com/auth/login'
]); ?>
    <?= $form->field($model, 'email')->textInput(['value' => 'test@user.demo']); ?>
    <?= $form->field($model, 'password')->passwordInput(['value' => '1234567A']); ?>
    <?= $form->field($model, 'curlname')->textInput(['value' => 'web-2015']); ?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Вход', ['class' => 'btn btn-primary']) ?>
        </div>
    </div>
<?php ActiveForm::end(); ?>

<script type="text/javascript">
    $('form#shaman-login1').on('beforeSubmit', function(e) {
        return false;
    }).on('submit', function(e){
        $.ajax({
            url  : 'test/login',
//            url  : $(this).attr('action'),
            type : 'POST',
//            data : $(this).serializeArray(),
            success : function(data){
                console.log(data);
            }
        });
    });
</script>

<?php
$js = <<<JS
// get the form id and set the event
$('form#shaman-login').on('beforeSubmit', function(e) {
    $.ajax({
        url  : 'test/login',
        type : 'POST',
        success : function(data)
        {
            data = JSON.parse(data);
            if(data && typeof data !='undefined')
            {
                console.log(data.token);
                var token = data.token;
                $.ajax({
                    url  : 'test/user',
                    type : 'POST',
                    data : {token:token},
                    success : function(data) {
                        data = JSON.parse(data);
                        console.log(data.secretKey);
                    }
                });
            }
        }
    });
    return false;
}).on('submit', function(e) {
    e.preventDefault();
});
JS;
 
$this->registerJs($js);

views/shaman/login.php
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<div class="site-login">
    <h1>Login int shaman api</h1>


    <div class="row">
        <div class="col-lg-5">
            <form class="shaman__api__login__form">
                <p>Email : <input type="text" name="email" value="test@user.demo"/></p>
                <p>Password: <input type="text" name="password" value="1234567A"/></p>
                <p>Curlname: <input type="text" name="curlname" value="web-2015"/></p>

            </form>
            <button class="btn btn-success shaman__api__login__btn">Login int shaman api</button>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body">
        <p>Some text in the modal.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<script>
$('.shaman__api__login__btn')
    .click(function(event) {
        var form = $('.shaman__api__login__form');
        $.ajax({
            url  : 'shaman/login',
            type : 'POST',
            data : $(form).serializeArray(),
            success: function(data) {
                data = JSON.parse(data);
                if(!data || typeof data.token == 'undefined')
                {
                    var html = '<p>'+data.name+'</p>';
                    html +='<p>'+data.message.email+'</p>';
                    $('#myModal .modal-body').text(html);
                    $('#myModal').modal('show');
                    console.log(data);
                    return false;
                }
                $.ajax({
                    url  : 'shaman/user',
                    type : 'POST',
                    data : { token:data.token },
                    success: function(data)
                    {
                        data = JSON.parse(data);
                        
                        var html = '';
                        if(!data || typeof data.id == 'undefined')
                        {
                            html += data.message;
                        } else {
                            html += 'Success Info';
                            html += '<p>ID: '    + data.id    + '</p>';
                            html += '<p>name: '  + data.name  + '</p>';
                            html += '<p>email: ' + data.email + '</p>';
                        }
                        $('#myModal .modal-body').text(html);
                        $('#myModal').modal('show');
                        console.log(data);
                    }
                });
            }
        });
    });
</script>

views/site/index.php
Hi shaman